name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download JDBC driver
      run: wget http://m.oiu.tv/build/clj-beq/ojdbc8.jar

    - name: Install JDBC driver
      run: mvn install:install-file -X -DgroupId=local -DartifactId=ojdbc8 -Dversion=19.3 -Dpackaging=jar -Dfile=ojdbc8.jar -DgeneratePom=true
      
    - name: Install dependencies
      run: lein deps
      
    - name: Build überjar
      run: lein uberjar

    - name: Get the name of the built jar
      run: echo "::set-env name=BUILT_JAR::$(ls target/clj-beq*-standalone.jar|head)"

    - name: Get the name of the release jar
      run: echo "::set-env REL_JAR::$(echo $BUILT_JAR |sed -e s/SNAPSHOT-standalone/$GITHUB_RUN_NUMBER/)"

    - name: Rename built jar
      run: mv ${BUILT_JAR} ${REL_JAR}
      